# Generated by Django 5.2.7 on 2025-10-24 12:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="about_preview",
            field=wagtail.fields.StreamField(
                [("about", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Summary text for the about section",
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("summary_text", 0), ("image", 1)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="blog_highlights",
            field=wagtail.fields.StreamField(
                [("blog_highlight", 1)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Latest from our Blog",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("title", 0)]], {}),
                },
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="final_cta",
            field=wagtail.fields.StreamField(
                [("cta", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Headline for the CTA section",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Subheadline for the CTA section",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Call to action button text",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Call to action button link", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 0),
                                ("subheadline", 1),
                                ("cta_text", 2),
                                ("cta_link", 3),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_section",
            field=wagtail.fields.StreamField(
                [("hero", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main headline for the hero section",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Subheadline for the hero section",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Call to action button text",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Call to action button link", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 0),
                                ("subheadline", 1),
                                ("background_image", 2),
                                ("cta_text", 3),
                                ("cta_link", 4),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="key_stats",
            field=wagtail.fields.StreamField(
                [("stat", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "The statistic number", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Label for the statistic",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("number", 0), ("label", 1)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="partners_carousel",
            field=wagtail.fields.StreamField(
                [("partner", 1)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("Partner",),
                        {"required": True},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("partner", 0)]], {}),
                },
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="services_overview",
            field=wagtail.fields.StreamField(
                [("service", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Service title",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Short description of the service",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link to service detail page", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 0), ("title", 1), ("description", 2), ("link", 3)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="testimonials_slider",
            field=wagtail.fields.StreamField(
                [("testimonial", 1)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("Testimonial",),
                        {"required": True},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("testimonial", 0)]], {}),
                },
            ),
        ),
    ]
