# Generated by Django 5.2.7 on 2025-10-24 13:22

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_about_preview_homepage_blog_highlights_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerCarousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Our Trusted Partners",
                        help_text="Title for the partners section",
                        max_length=100,
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Subtitle for the partners section",
                        max_length=200,
                    ),
                ),
                (
                    "autoplay",
                    models.BooleanField(
                        default=True, help_text="Enable autoplay for the carousel"
                    ),
                ),
                (
                    "autoplay_delay",
                    models.IntegerField(
                        default=5000, help_text="Autoplay delay in milliseconds"
                    ),
                ),
                (
                    "loop",
                    models.BooleanField(
                        default=True, help_text="Enable loop for the carousel"
                    ),
                ),
                (
                    "show_navigation",
                    models.BooleanField(
                        default=True, help_text="Show navigation arrows"
                    ),
                ),
                (
                    "show_pagination",
                    models.BooleanField(
                        default=False, help_text="Show pagination dots"
                    ),
                ),
                (
                    "partners_per_view_mobile",
                    models.IntegerField(
                        default=2, help_text="Number of partners to show on mobile"
                    ),
                ),
                (
                    "partners_per_view_tablet",
                    models.IntegerField(
                        default=3, help_text="Number of partners to show on tablet"
                    ),
                ),
                (
                    "partners_per_view_desktop",
                    models.IntegerField(
                        default=5, help_text="Number of partners to show on desktop"
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner Carousel",
                "verbose_name_plural": "Partner Carousels",
            },
        ),
        migrations.AlterField(
            model_name="homepage",
            name="partners_carousel",
            field=wagtail.fields.StreamField(
                [("partner", 1), ("partner_carousel", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.Partner",),
                        {"required": True},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("partner", 0)]], {}),
                    2: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.PartnerCarousel",),
                        {"required": True},
                    ),
                    3: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.Partner",),
                        {},
                    ),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("carousel", 2), ("partners", 4)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="testimonials_slider",
            field=wagtail.fields.StreamField(
                [("testimonial", 1)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.Testimonial",),
                        {"required": True},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("testimonial", 0)]], {}),
                },
            ),
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the partner", max_length=100),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="Website of the partner"),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Feature this partner prominently"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Logo of the partner",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
                "ordering": ["-featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the person giving the testimonial",
                        max_length=100,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Role/position of the person",
                        max_length=100,
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, help_text="Company of the person", max_length=100
                    ),
                ),
                ("quote", models.TextField(help_text="The testimonial quote")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Profile image of the person",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["-created_at"],
            },
        ),
    ]
