# Generated by Django 5.2.7 on 2025-10-24 13:34

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_partnercarousel_alter_homepage_partners_carousel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestimonialCarousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="What Our Clients Say",
                        help_text="Title for the testimonials section",
                        max_length=100,
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Subtitle for the testimonials section",
                        max_length=200,
                    ),
                ),
                (
                    "autoplay",
                    models.BooleanField(
                        default=True, help_text="Enable autoplay for the carousel"  # type: ignore
                    ),
                ),
                (
                    "autoplay_delay",
                    models.IntegerField(
                        default=5000, help_text="Autoplay delay in milliseconds"  # type: ignore
                    ),
                ),
                (
                    "loop",
                    models.BooleanField(
                        default=True, help_text="Enable loop for the carousel"  # type: ignore
                    ),
                ),
                (
                    "show_navigation",
                    models.BooleanField(
                        default=True, help_text="Show navigation arrows"  # type: ignore
                    ),
                ),
                (
                    "show_pagination",
                    models.BooleanField(default=True, help_text="Show pagination dots"),  # type: ignore
                ),
                (
                    "testimonials_per_view_mobile",
                    models.IntegerField(
                        default=1, help_text="Number of testimonials to show on mobile"  # type: ignore
                    ),
                ),
                (
                    "testimonials_per_view_tablet",
                    models.IntegerField(
                        default=2, help_text="Number of testimonials to show on tablet"  # type: ignore
                    ),
                ),
                (
                    "testimonials_per_view_desktop",
                    models.IntegerField(
                        default=3, help_text="Number of testimonials to show on desktop"  # type: ignore
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonial Carousel",
                "verbose_name_plural": "Testimonial Carousels",
            },
        ),
        migrations.AlterModelOptions(
            name="testimonial",
            options={
                "ordering": ["sort_order", "-created_at"],
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
            },
        ),
        migrations.AddField(
            model_name="testimonial",
            name="is_visible",
            field=models.BooleanField(
                default=True, help_text="Show this testimonial on the website"  # type: ignore
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="sort_order",
            field=models.IntegerField(
                default=0, help_text="Ordering priority (lower numbers first)"  # type: ignore
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="star_rating",
            field=models.IntegerField(
                choices=[
                    (1, "1 Star"),
                    (2, "2 Stars"),
                    (3, "3 Stars"),
                    (4, "4 Stars"),
                    (5, "5 Stars"),
                ],
                default=5,  # type: ignore
                help_text="Star rating (1-5)",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="testimonials_slider",
            field=wagtail.fields.StreamField(
                [("testimonial", 1), ("testimonial_carousel", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.Testimonial",),
                        {"required": True},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("testimonial", 0)]], {}),
                    2: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.TestimonialCarousel",),
                        {"required": True},
                    ),
                    3: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.Testimonial",),
                        {},
                    ),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("carousel", 2), ("testimonials", 4)]],
                        {},
                    ),
                },
            ),
        ),
    ]