# Generated by Django 5.2.7 on 2025-10-24 13:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_testimonialcarousel_alter_testimonial_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="final_cta",
            field=wagtail.fields.StreamField(
                [("cta", 4), ("full_width_cta", 12)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Headline for the CTA section",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Subheadline for the CTA section",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Call to action button text",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Call to action button link", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 0),
                                ("subheadline", 1),
                                ("cta_text", 2),
                                ("cta_link", 3),
                            ]
                        ],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main heading for the CTA banner",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Subheading for the CTA banner",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text for the CTA button",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    8: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "URL for the CTA button", "required": True},
                    ),
                    9: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Background image for the CTA banner",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "rgba(0, 0, 0, 0.7)",
                            "help_text": "Overlay color in hex format (e.g., #000000). Leave empty for default.",
                            "max_length": 7,
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("light", "Light Theme"),
                                ("dark", "Dark Theme"),
                            ],
                            "help_text": "Select the theme variant for text and button styling",
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 5),
                                ("subheading", 6),
                                ("button_text", 7),
                                ("button_link", 8),
                                ("background_image", 9),
                                ("overlay_color", 10),
                                ("theme_variant", 11),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
