# Generated by Django 5.2.7 on 2025-10-24 14:27

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_homepage_final_cta"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PartnerCarousel",
        ),
        migrations.DeleteModel(
            name="TestimonialCarousel",
        ),
        migrations.AlterModelOptions(
            name="testimonial",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
            },
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="is_visible",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="sort_order",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="star_rating",
        ),
        migrations.AddField(
            model_name="homepage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image to be used for social media sharing (Open Graph and Twitter cards)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="twitter_card_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("summary", "Summary"),
                    ("summary_large_image", "Summary with Large Image"),
                ],
                default="summary_large_image",
                help_text="Type of Twitter card to use",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="final_cta",
            field=wagtail.fields.StreamField(
                [("cta", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Headline for the CTA section",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Subheadline for the CTA section",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Call to action button text",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Call to action button link", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 0),
                                ("subheadline", 1),
                                ("cta_text", 2),
                                ("cta_link", 3),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="partners_carousel",
            field=wagtail.fields.StreamField(
                [("partner", 1)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.Partner",),
                        {"required": True},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("partner", 0)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="testimonials_slider",
            field=wagtail.fields.StreamField(
                [("testimonial", 1)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.Testimonial",),
                        {"required": True},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("testimonial", 0)]], {}),
                },
            ),
        ),
    ]
