# Generated by Django 5.2.7 on 2025-10-24 14:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_delete_partnercarousel_delete_testimonialcarousel_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage",
            old_name="about_preview",
            new_name="about_summary",
        ),
        migrations.RenameField(
            model_name="homepage",
            old_name="final_cta",
            new_name="call_to_action",
        ),
        migrations.RenameField(
            model_name="homepage",
            old_name="blog_highlights",
            new_name="latest_news",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="key_stats",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="partners_carousel",
        ),
        migrations.AddField(
            model_name="homepage",
            name="case_studies",
            field=wagtail.fields.StreamField(
                [("case_study", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title of the project",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Brief description of the project",
                            "max_length": 300,
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Featured image of the project",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Link to detailed project page",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Name of the client",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("project_title", 0),
                                ("short_description", 1),
                                ("project_image", 2),
                                ("project_link", 3),
                                ("client_name", 4),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="industries_served",
            field=wagtail.fields.StreamField(
                [("industry", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Name of the industry",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Logo or icon representing the industry",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Brief description of our work in this industry",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 0), ("logo_or_icon", 1), ("description", 2)]],
                        {},
                    ),
                },
            ),
        ),
    ]
